version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: python --version
      - run: sudo apt-get update
      - run: sudo apt install libespeak-dev
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest


workflows:
  run_test_cases:
    jobs:
      - build-and-test
